version: '3'

services:
    nginx:
        restart: always
        image: nginx:1.25-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/likesoft/static
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/server-entrypoint.sh
        volumes:
            - static_volume:/app/likesoft/static
        expose:
            - 8000
        env_file:
          - .env

    worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/worker-entrypoint.sh
        volumes:
            - static_volume:/app/likesoft/static
        env_file:
          - .env
        depends_on:
            - server
            - redis

    redis:
        restart: unless-stopped
        image: redis:7.2.3-alpine
        expose:
            - 6379
    db:
        image: mysql:latest
        restart: unless-stopped
        volumes:
            - db_data:/var/lib/mysql
        env_file:
          - .env
        expose:
            - 5432

volumes:
    static_volume: {}
    db_data: {}
